package com.mie.controller;

import com.mie.dao.CompanyDao;
import com.mie.dao.EventDao;
import com.mie.model.Event;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.Time;

public class EventController extends HttpServlet {

	private static final long serialVersionUID = 1L;
	private static String INSERT = "/event/add.jsp";
	
	//not going to be able to edit event
	//private static String EDIT = "/event/edit.jsp";
	private static String LIST_EVENT_PUBLIC = "/event/listPublic.jsp";
	private static String LIST_EVENT_ADMIN = "/event/listAdmin.jsp";

	private EventDao dao;
	private CompanyDao companyDao;

	/**
	 * Constructor for this class.
	 */
	public EventController() {
		super();
		dao = new EventDao();
		companyDao = new CompanyDao();
	}

	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		String forward = "";
		String action = request.getParameter("action");

		if (action.equalsIgnoreCase("insert")) {
			forward = INSERT;
			request.setAttribute("startups", companyDao.getAllCompanies());
		} else if (action.equalsIgnoreCase("listEventAdmin")) {
			forward = LIST_EVENT_ADMIN; //may need to change this dependent on front end changes
			request.setAttribute("events", dao.getAllEvents());
		} else {
			forward = INSERT;
		}

		RequestDispatcher view = request.getRequestDispatcher(forward);
		view.forward(request, response);
	}

	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		// Check if they are logged in

		Event event = new Event();
		
		event.setEventName(request.getParameter("eventName"));
		event.setLocation(request.getParameter("location"));
		event.setDescription(request.getParameter("description"));
		event.setStartupId(Integer.parseInt(request.getParameter("startup")));

		//sets the date
		try {
			Date date = new SimpleDateFormat("MM/dd/yyyy").parse(request
					.getParameter("eventDate"));
			event.setDate(date);
		} catch (ParseException e) {
			e.printStackTrace();
		}
		
		//need to figure out how to set the time of the event 
		event.setEventTime(request.getParameter("eventTime"));

		/*
		try{
			Time time = new SimpleTimeFormat('')
		}catch (ParseException e){
			e.printStackTrace();
		}*/



		//need to test if it actually just generates ID 
		//this should actually disappear if it's autogenerated number in database

		String eventId = request.getParameter("eventId"); //is this eventId or eventID
		//this needs to be an integer right?
		
		
		//only add it when this event DNE
		if (eventId == null || eventId.isEmpty()) {
			dao.addEvent(event);
		} 
		
		
		/*else {
			event.setEventId(Integer.parseInt(eventid));
			dao.updateEvent(event);
		}*/

		RequestDispatcher view = request
				.getRequestDispatcher(LIST_EVENT_ADMIN);

		request.setAttribute("events", dao.getAllEvents());

		view.forward(request, response);
	}
}